### ISSUE TITLE
Hashing time.Time does not generate unique hashes

### ISSUE THREAD

**Issue by tnine** [mitchellh/hashstructure#16]
See included ginkgo test case.  2 Different times return the same hash

```golang
It("hashes time differently", func() {
			t1 := time.Now()
			t2 := t1.Add(1 * time.Second)

			hashedT1, err := hashstructure.Hash(t1, nil)
			Expect(err).Should(BeNil())

			hashedT2, err := hashstructure.Hash(t2, nil)
			Expect(err).Should(BeNil())

			Expect(hashedT1).ShouldNot(Equal(hashedT2))
		})
```

**Comment by mitchellh** [comment]
Hm, we tested this awhile back and it worked but I wonder if this is due to the recent (somewhat, a couple Go releases ago) changes to time to support monotonic clocks... Thanks for reporting this I'll take a look.

**Comment by F21** [comment]
I wonder if this is because `time.Time` does not have any exported properties, so a hash of the struct it not able to be generated.

In the tests, there is a [test to test time.Time](https://github.com/mitchellh/hashstructure/blob/master/hashstructure_test.go#L250) without forcing it to a string using a tag. Should the expected result be `false` rather than `true`?

I don't think this is an issue with the change to monotonic clocks, but rather the time struct does not have any exported properties and since hashstructure will not be able to read those properties, the generated hash is always the same.

A possible solution might be to add a special case to handle `time.Time` as strings.

If the `time.Time` is a property in a struct, it's possible to work around it by forcing it to a string using `hash:"string"`, however this does not help if you're interested in passing a `time.Time` directly to `Hash()`.
